import type { User, AuctionDetail } from "../types/auction";

export const MOCK_USERS: User[] = [
  {
    id: "user-001",
    displayName: "TechTrader99",
    sellerRatingPercent: 99.8,
    sellerFeedbackCount: 2341,
    sellerLocation: "San Francisco, CA",
    paymentVerified: true,
  },
  {
    id: "user-002",
    displayName: "VintageFinds",
    sellerRatingPercent: 100,
    sellerFeedbackCount: 4892,
    sellerLocation: "Brooklyn, NY",
    paymentVerified: true,
  },
  {
    id: "user-003",
    displayName: "LuxWatchCo",
    sellerRatingPercent: 99.5,
    sellerFeedbackCount: 812,
    sellerLocation: "Miami, FL",
    paymentVerified: true,
  },
  {
    id: "user-004",
    displayName: "SportsMemorabilia",
    sellerRatingPercent: 98.7,
    sellerFeedbackCount: 1567,
    sellerLocation: "Chicago, IL",
    paymentVerified: true,
  },
  {
    id: "user-005",
    displayName: "DesignerDeals",
    sellerRatingPercent: 99.2,
    sellerFeedbackCount: 3204,
    sellerLocation: "Los Angeles, CA",
    paymentVerified: true,
  },
];

function hoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function daysFromNow(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

export const MOCK_AUCTIONS: AuctionDetail[] = [
  {
    id: "a001",
    title: "Canon AE-1 Program 35mm Film Camera w/ 50mm f/1.8 Lens",
    category: "Cameras",
    condition: "Used - Excellent",
    brand: "Canon",
    imageUrls: [
      "https://picsum.photos/seed/canon-ae1-1/600/400",
      "https://picsum.photos/seed/canon-ae1-2/600/400",
      "https://picsum.photos/seed/canon-ae1-3/600/400",
      "https://picsum.photos/seed/canon-ae1-4/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 75.0,
    currentPrice: 189.5,
    buyNowPrice: 350.0,
    endsAt: hoursFromNow(2.5),
    status: "ACTIVE",
    bidCount: 14,
    watchCount: 42,
    sellerId: "user-002",
    sellerDisplayName: "VintageFinds",
    sellerRatingPercent: 100,
    sellerFeedbackCount: 4892,
    sellerLocation: "Brooklyn, NY",
    shippingMode: "Standard",
    shippingCostPayer: "buyer",
    shippingCostMin: 12.99,
    shippingCostMax: 12.99,
    returnsAccepted: true,
    returnsPolicyLabel: "30-day returns accepted",
    description:
      "Beautiful Canon AE-1 Program in excellent working condition. This iconic 35mm SLR camera comes with the original Canon FD 50mm f/1.8 lens. Shutter fires accurately at all speeds. Light meter is responsive and accurate. Film advance is smooth. Cosmetically in great shape with only minor signs of use. Includes original body cap and rear lens cap. A perfect camera for film photography enthusiasts or collectors.",
    model: "AE-1 Program",
    year: 1981,
    itemSpecifics: {
      "Film Format": "35mm",
      "Focus Type": "Manual Focus",
      "Lens Mount": "Canon FD",
      "Shutter Type": "Focal Plane",
      "Metering Type": "Center-weighted",
      "Battery Type": "A544 / 4LR44",
      "Included Lens": "Canon FD 50mm f/1.8",
      "Country of Manufacture": "Japan",
    },
    shippingService: "USPS Priority Mail",
    handlingDays: 1,
    estimatedDeliveryMinDays: 3,
    estimatedDeliveryMaxDays: 5,
    itemLocationZip: "11201",
    internationalShipping: true,
    paymentMethodLabel: "PayPal, Credit Card",
    bids: [
      { id: "b001", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 189.5, createdAt: minutesAgo(12), isLeading: true },
      { id: "b002", userId: "user-004", userDisplayName: "SportsMemorabilia", visiblePriceSnapshot: 175.0, createdAt: minutesAgo(45), isLeading: false },
      { id: "b003", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 155.0, createdAt: minutesAgo(120), isLeading: false },
      { id: "b004", userId: "user-005", userDisplayName: "DesignerDeals", visiblePriceSnapshot: 140.0, createdAt: minutesAgo(180), isLeading: false },
      { id: "b005", userId: "user-004", userDisplayName: "SportsMemorabilia", visiblePriceSnapshot: 120.0, createdAt: minutesAgo(300), isLeading: false },
    ],
    isWatched: false,
  },
  {
    id: "a002",
    title: 'Apple MacBook Pro 14" M3 Pro 18GB 512GB Space Black - Like New',
    category: "Electronics",
    condition: "Used - Like New",
    brand: "Apple",
    imageUrls: [
      "https://picsum.photos/seed/macbook-m3-1/600/400",
      "https://picsum.photos/seed/macbook-m3-2/600/400",
      "https://picsum.photos/seed/macbook-m3-3/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 1200.0,
    currentPrice: 1485.0,
    endsAt: daysFromNow(3),
    status: "ACTIVE",
    bidCount: 23,
    watchCount: 87,
    sellerId: "user-001",
    sellerDisplayName: "TechTrader99",
    sellerRatingPercent: 99.8,
    sellerFeedbackCount: 2341,
    sellerLocation: "San Francisco, CA",
    shippingMode: "Free",
    shippingCostPayer: "seller",
    shippingCostMin: 0,
    shippingCostMax: 0,
    returnsAccepted: true,
    returnsPolicyLabel: "30-day returns accepted",
    description:
      "Selling my MacBook Pro 14-inch with the M3 Pro chip. Purchased in October 2024, used lightly for about 3 months. Battery cycle count is only 47. Comes with original box, charger, and USB-C cable. Screen is flawless with no scratches. Keyboard and trackpad in perfect condition. AppleCare+ eligible until October 2027. Reason for selling: upgraded to M3 Max model.",
    model: "MacBook Pro 14-inch",
    year: 2024,
    itemSpecifics: {
      Processor: "Apple M3 Pro (11-core)",
      RAM: "18GB Unified Memory",
      Storage: "512GB SSD",
      Display: '14.2" Liquid Retina XDR',
      "Battery Cycles": "47",
      Color: "Space Black",
      "Operating System": "macOS Sonoma",
    },
    shippingService: "FedEx Ground",
    handlingDays: 1,
    estimatedDeliveryMinDays: 2,
    estimatedDeliveryMaxDays: 5,
    itemLocationZip: "94107",
    internationalShipping: false,
    paymentMethodLabel: "PayPal, Credit Card",
    bids: [
      { id: "b006", userId: "user-003", userDisplayName: "LuxWatchCo", visiblePriceSnapshot: 1485.0, createdAt: minutesAgo(30), isLeading: true },
      { id: "b007", userId: "user-005", userDisplayName: "DesignerDeals", visiblePriceSnapshot: 1450.0, createdAt: minutesAgo(90), isLeading: false },
      { id: "b008", userId: "user-003", userDisplayName: "LuxWatchCo", visiblePriceSnapshot: 1400.0, createdAt: minutesAgo(200), isLeading: false },
    ],
    isWatched: true,
  },
  {
    id: "a003",
    title: "Rolex Submariner Date 126610LN 41mm Black Dial 2023",
    category: "Watches",
    condition: "Used - Very Good",
    brand: "Rolex",
    imageUrls: [
      "https://picsum.photos/seed/rolex-sub-1/600/400",
      "https://picsum.photos/seed/rolex-sub-2/600/400",
      "https://picsum.photos/seed/rolex-sub-3/600/400",
      "https://picsum.photos/seed/rolex-sub-4/600/400",
      "https://picsum.photos/seed/rolex-sub-5/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 8000.0,
    currentPrice: 12750.0,
    buyNowPrice: 14500.0,
    endsAt: hoursFromNow(0.75),
    status: "ACTIVE",
    bidCount: 31,
    watchCount: 156,
    sellerId: "user-003",
    sellerDisplayName: "LuxWatchCo",
    sellerRatingPercent: 99.5,
    sellerFeedbackCount: 812,
    sellerLocation: "Miami, FL",
    shippingMode: "Insured",
    shippingCostPayer: "seller",
    shippingCostMin: 0,
    shippingCostMax: 0,
    returnsAccepted: true,
    returnsPolicyLabel: "14-day returns, buyer pays return shipping",
    description:
      "Authentic Rolex Submariner Date reference 126610LN. Purchased new from authorized dealer in March 2023. Comes as full set: inner/outer box, warranty card (dated March 2023), hang tag, booklets, and green Rolex sleeve. Watch is in very good condition with light desk-diving marks on the bracelet and clasp. Crystal is flawless. Bezel insert is perfect. Movement is running within COSC specs. 41mm Oystersteel case with black Cerachrom bezel.",
    model: "Submariner Date 126610LN",
    year: 2023,
    itemSpecifics: {
      "Case Size": "41mm",
      "Case Material": "Oystersteel",
      Movement: "Rolex Caliber 3235 Automatic",
      "Water Resistance": "300m / 1000ft",
      "Bezel Material": "Cerachrom (Ceramic)",
      "Bracelet Type": "Oyster with Glidelock",
      "Dial Color": "Black",
      "Power Reserve": "70 hours",
    },
    shippingService: "FedEx Overnight (Insured)",
    handlingDays: 1,
    estimatedDeliveryMinDays: 1,
    estimatedDeliveryMaxDays: 2,
    itemLocationZip: "33139",
    internationalShipping: false,
    paymentMethodLabel: "Wire Transfer, PayPal",
    bids: [
      { id: "b009", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 12750.0, createdAt: minutesAgo(8), isLeading: true },
      { id: "b010", userId: "user-002", userDisplayName: "VintageFinds", visiblePriceSnapshot: 12500.0, createdAt: minutesAgo(15), isLeading: false },
      { id: "b011", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 12000.0, createdAt: minutesAgo(60), isLeading: false },
      { id: "b012", userId: "user-005", userDisplayName: "DesignerDeals", visiblePriceSnapshot: 11500.0, createdAt: minutesAgo(120), isLeading: false },
    ],
    isWatched: false,
  },
  {
    id: "a004",
    title: "1986 Topps Baseball Complete Set - 792 Cards - Mint Condition",
    category: "Collectibles",
    condition: "New",
    brand: "Topps",
    imageUrls: [
      "https://picsum.photos/seed/topps-1986-1/600/400",
      "https://picsum.photos/seed/topps-1986-2/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 150.0,
    currentPrice: 285.0,
    endsAt: daysFromNow(5),
    status: "ACTIVE",
    bidCount: 8,
    watchCount: 34,
    sellerId: "user-004",
    sellerDisplayName: "SportsMemorabilia",
    sellerRatingPercent: 98.7,
    sellerFeedbackCount: 1567,
    sellerLocation: "Chicago, IL",
    shippingMode: "Standard",
    shippingCostPayer: "buyer",
    shippingCostMin: 8.99,
    shippingCostMax: 8.99,
    returnsAccepted: true,
    returnsPolicyLabel: "60-day returns accepted",
    description:
      "Complete 1986 Topps Baseball card set featuring 792 cards in near-mint to mint condition. Includes key rookies: Barry Bonds #11T, Bo Jackson, Jose Canseco, and more. Cards have been stored in a cool, dry environment since purchase. Hand-sorted and collated. Set includes factory variations. A must-have for any serious baseball card collector. Cards are stored in plastic pages within a binder for protection.",
    itemSpecifics: {
      Sport: "Baseball",
      Year: "1986",
      Set: "Complete (792 cards)",
      Manufacturer: "Topps",
      "Key Rookies": "Bonds, Jackson, Canseco",
      "Card Condition": "Near Mint to Mint",
      Graded: "No - Raw",
    },
    shippingService: "USPS Priority Mail",
    handlingDays: 2,
    estimatedDeliveryMinDays: 3,
    estimatedDeliveryMaxDays: 7,
    itemLocationZip: "60614",
    internationalShipping: true,
    paymentMethodLabel: "PayPal, Credit Card",
    bids: [
      { id: "b013", userId: "user-002", userDisplayName: "VintageFinds", visiblePriceSnapshot: 285.0, createdAt: minutesAgo(300), isLeading: true },
      { id: "b014", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 250.0, createdAt: minutesAgo(400), isLeading: false },
    ],
    isWatched: false,
  },
  {
    id: "a005",
    title: "Nike Air Jordan 1 Retro High OG 'Chicago' 2023 - Size 10 DS",
    category: "Fashion",
    condition: "New with Tags",
    brand: "Nike",
    imageUrls: [
      "https://picsum.photos/seed/jordan-chi-1/600/400",
      "https://picsum.photos/seed/jordan-chi-2/600/400",
      "https://picsum.photos/seed/jordan-chi-3/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 250.0,
    currentPrice: 425.0,
    buyNowPrice: 550.0,
    endsAt: hoursFromNow(18),
    status: "ACTIVE",
    bidCount: 19,
    watchCount: 73,
    sellerId: "user-005",
    sellerDisplayName: "DesignerDeals",
    sellerRatingPercent: 99.2,
    sellerFeedbackCount: 3204,
    sellerLocation: "Los Angeles, CA",
    shippingMode: "Free",
    shippingCostPayer: "seller",
    shippingCostMin: 0,
    shippingCostMax: 0,
    returnsAccepted: false,
    returnsPolicyLabel: "No returns accepted",
    description:
      "Deadstock Nike Air Jordan 1 Retro High OG 'Chicago' (2023 reimagined release). Men's size 10 / EU 44. Never worn, never tried on. Comes with original box, extra laces (black and white), and tissue paper. Purchased directly from Nike SNKRS app. 100% authentic guaranteed. The iconic Chicago colorway in premium leather.",
    model: "Air Jordan 1 Retro High OG",
    year: 2023,
    itemSpecifics: {
      Size: "US Men's 10 / EU 44",
      Color: "Varsity Red/Black-White",
      "Style Code": "DZ5485-612",
      "Release Date": "October 2023",
      "Upper Material": "Premium Leather",
      "Sole Type": "Rubber",
      Closure: "Lace-Up",
    },
    shippingService: "UPS Ground",
    handlingDays: 1,
    estimatedDeliveryMinDays: 3,
    estimatedDeliveryMaxDays: 5,
    itemLocationZip: "90028",
    internationalShipping: true,
    paymentMethodLabel: "PayPal, Credit Card",
    bids: [
      { id: "b015", userId: "user-004", userDisplayName: "SportsMemorabilia", visiblePriceSnapshot: 425.0, createdAt: minutesAgo(60), isLeading: true },
      { id: "b016", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 400.0, createdAt: minutesAgo(90), isLeading: false },
      { id: "b017", userId: "user-003", userDisplayName: "LuxWatchCo", visiblePriceSnapshot: 375.0, createdAt: minutesAgo(150), isLeading: false },
    ],
    isWatched: true,
  },
  {
    id: "a006",
    title: "Sony A7 III Mirrorless Camera Body Only - Low Shutter Count",
    category: "Cameras",
    condition: "Used - Good",
    brand: "Sony",
    imageUrls: [
      "https://picsum.photos/seed/sony-a7iii-1/600/400",
      "https://picsum.photos/seed/sony-a7iii-2/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 800.0,
    currentPrice: 1025.0,
    endsAt: daysFromNow(1.5),
    status: "ACTIVE",
    bidCount: 11,
    watchCount: 51,
    sellerId: "user-001",
    sellerDisplayName: "TechTrader99",
    sellerRatingPercent: 99.8,
    sellerFeedbackCount: 2341,
    sellerLocation: "San Francisco, CA",
    shippingMode: "Standard",
    shippingCostPayer: "buyer",
    shippingCostMin: 14.99,
    shippingCostMax: 14.99,
    returnsAccepted: true,
    returnsPolicyLabel: "30-day returns accepted",
    description:
      "Sony A7 III full-frame mirrorless camera body. Shutter count approximately 12,400 - well below the 200,000 rated shutter life. Sensor is clean with no dust spots. LCD has a screen protector (can be removed). EVF is clear and bright. All ports function correctly. Includes original battery, charger, strap, and body cap. No box. Upgraded to A7R V, so this needs a new home.",
    model: "A7 III (ILCE-7M3)",
    year: 2018,
    itemSpecifics: {
      "Sensor Type": "Full Frame CMOS",
      Megapixels: "24.2 MP",
      "ISO Range": "100-51200 (expandable)",
      "Autofocus Points": "693 Phase-Detection",
      "Video Resolution": "4K 30fps",
      "Shutter Count": "~12,400",
      "Lens Mount": "Sony E-mount",
    },
    shippingService: "USPS Priority Mail",
    handlingDays: 1,
    estimatedDeliveryMinDays: 3,
    estimatedDeliveryMaxDays: 5,
    itemLocationZip: "94107",
    internationalShipping: true,
    paymentMethodLabel: "PayPal, Credit Card",
    bids: [
      { id: "b018", userId: "user-002", userDisplayName: "VintageFinds", visiblePriceSnapshot: 1025.0, createdAt: minutesAgo(180), isLeading: true },
      { id: "b019", userId: "user-005", userDisplayName: "DesignerDeals", visiblePriceSnapshot: 975.0, createdAt: minutesAgo(300), isLeading: false },
    ],
    isWatched: false,
  },
  {
    id: "a007",
    title: "Signed Michael Jordan 1997 NBA Finals Basketball - UDA Authenticated",
    category: "Sports",
    condition: "Used - Like New",
    brand: "Spalding",
    imageUrls: [
      "https://picsum.photos/seed/mj-ball-1/600/400",
      "https://picsum.photos/seed/mj-ball-2/600/400",
      "https://picsum.photos/seed/mj-ball-3/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 2000.0,
    currentPrice: 3850.0,
    endsAt: hoursFromNow(6),
    status: "ACTIVE",
    bidCount: 16,
    watchCount: 92,
    sellerId: "user-004",
    sellerDisplayName: "SportsMemorabilia",
    sellerRatingPercent: 98.7,
    sellerFeedbackCount: 1567,
    sellerLocation: "Chicago, IL",
    shippingMode: "Free",
    shippingCostPayer: "seller",
    shippingCostMin: 0,
    shippingCostMax: 0,
    returnsAccepted: true,
    returnsPolicyLabel: "14-day returns accepted",
    description:
      "Michael Jordan autographed Spalding official NBA Finals basketball from the 1997 season. Authenticated by Upper Deck Authenticated (UDA) with hologram sticker and matching certificate of authenticity. Signature is bold and clean in silver paint pen. Basketball is in display-quality condition. Comes in original UDA packaging. A centerpiece item for any serious Jordan or NBA collection.",
    itemSpecifics: {
      Sport: "Basketball",
      "Player/Athlete": "Michael Jordan",
      "Authentication": "Upper Deck (UDA)",
      "Signature Type": "Silver Paint Pen",
      Season: "1997 NBA Finals",
      League: "NBA",
      "Ball Type": "Official NBA Game Ball",
    },
    shippingService: "FedEx Ground (Insured)",
    handlingDays: 2,
    estimatedDeliveryMinDays: 3,
    estimatedDeliveryMaxDays: 7,
    itemLocationZip: "60614",
    internationalShipping: false,
    paymentMethodLabel: "PayPal, Wire Transfer",
    bids: [
      { id: "b020", userId: "user-003", userDisplayName: "LuxWatchCo", visiblePriceSnapshot: 3850.0, createdAt: minutesAgo(25), isLeading: true },
      { id: "b021", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 3600.0, createdAt: minutesAgo(60), isLeading: false },
      { id: "b022", userId: "user-005", userDisplayName: "DesignerDeals", visiblePriceSnapshot: 3200.0, createdAt: minutesAgo(180), isLeading: false },
    ],
    isWatched: false,
  },
  {
    id: "a008",
    title: "Omega Speedmaster Professional Moonwatch 3570.50 - CLOSED",
    category: "Watches",
    condition: "Used - Very Good",
    brand: "Omega",
    imageUrls: [
      "https://picsum.photos/seed/omega-speed-1/600/400",
      "https://picsum.photos/seed/omega-speed-2/600/400",
    ],
    listingFormat: "Auction",
    startingPrice: 3000.0,
    currentPrice: 4625.0,
    endsAt: daysAgo(1),
    status: "CLOSED",
    bidCount: 22,
    watchCount: 68,
    sellerId: "user-003",
    sellerDisplayName: "LuxWatchCo",
    sellerRatingPercent: 99.5,
    sellerFeedbackCount: 812,
    sellerLocation: "Miami, FL",
    shippingMode: "Insured",
    shippingCostPayer: "seller",
    shippingCostMin: 0,
    shippingCostMax: 0,
    returnsAccepted: true,
    returnsPolicyLabel: "14-day returns, buyer pays return shipping",
    description:
      "Omega Speedmaster Professional 'Moonwatch' ref. 3570.50. Manual wind caliber 1861 movement. 42mm stainless steel case on Omega stainless steel bracelet with extra links. Hesalite crystal. All pushers and crown function perfectly. Chronograph resets to zero cleanly. Watch was serviced in 2022 with receipts. Comes with Omega box and pictogram card. Classic tool watch in great condition.",
    model: "Speedmaster Professional 3570.50",
    year: 2019,
    itemSpecifics: {
      "Case Size": "42mm",
      "Case Material": "Stainless Steel",
      Movement: "Omega Caliber 1861 Manual Wind",
      Crystal: "Hesalite (Acrylic)",
      "Water Resistance": "50m",
      Chronograph: "Yes",
      "Last Serviced": "2022",
    },
    shippingService: "FedEx Overnight (Insured)",
    handlingDays: 1,
    estimatedDeliveryMinDays: 1,
    estimatedDeliveryMaxDays: 2,
    itemLocationZip: "33139",
    internationalShipping: false,
    paymentMethodLabel: "Wire Transfer, PayPal",
    bids: [
      { id: "b023", userId: "user-002", userDisplayName: "VintageFinds", visiblePriceSnapshot: 4625.0, createdAt: daysAgo(1), isLeading: true },
      { id: "b024", userId: "user-001", userDisplayName: "TechTrader99", visiblePriceSnapshot: 4500.0, createdAt: daysAgo(1), isLeading: false },
      { id: "b025", userId: "user-004", userDisplayName: "SportsMemorabilia", visiblePriceSnapshot: 4200.0, createdAt: daysAgo(1.1), isLeading: false },
    ],
    isWatched: false,
  },
];

export const CATEGORIES = [
  "All Categories",
  "Cameras",
  "Collectibles",
  "Electronics",
  "Fashion",
  "Sports",
  "Watches",
];
